import nodemailer from 'nodemailer';

// Configure the transporter
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: Number(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Sends an assignment generated by VedaAI to a list of emails.
 */
export async function sendAssignmentEmails(
  toEmails: string[],
  groupName: string,
  assignmentTitle: string,
  teacherName: string,
  pdfBuffer: Buffer // Or just HTML for now, depending on how we handle the assignment
): Promise<boolean> {
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    console.warn("SMTP credentials not set. Simulating email send instead.");
    console.log(`Simulated Email to ${toEmails.join(', ')} for Assignment: ${assignmentTitle}`);
    return true;
  }

  try {
    const mailOptions = {
      from: `"VedaAI Teacher Toolkit" <${process.env.SMTP_USER}>`,
      to: toEmails.join(','), // Send as comma separated
      subject: `New Assignment from ${teacherName}: ${assignmentTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 12px;">
          <h2 style="color: #111827; margin-bottom: 24px;">You have a new assignment!</h2>
          <p style="color: #374151; font-size: 16px; line-height: 1.5;">
            Hello from VedaAI! Your teacher, <strong>${teacherName}</strong>, has shared a new assignment with the <strong>${groupName}</strong> group.
          </p>
          <div style="background-color: #f9fafb; padding: 16px; border-radius: 8px; margin: 24px 0;">
            <p style="margin: 0; font-weight: bold; color: #111827;">Assignment Title:</p>
            <p style="margin: 4px 0 0 0; color: #4b5563;">${assignmentTitle}</p>
          </div>
          <p style="color: #374151; font-size: 16px; line-height: 1.5;">
            Please find the assignment attached as a PDF document. Good luck!
          </p>
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 32px 0;" />
          <p style="color: #9ca3af; font-size: 12px; text-align: center;">
            Sent automatically via VedaAI
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `${assignmentTitle}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf',
        }
      ]
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`Emails sent to group ${groupName} successfully. MessageId: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error("Error sending emails:", error);
    throw error;
  }
}
